version: '3.8'
# 声明一个名为network的networks,subnet为network的子网地址,默认网关是172.21.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '192.168.0.0/16'
## 遇到容器不停重启，首先怀疑是挂载目录读写执行权限问题
services:
  #### kafka ####
  # kafka 不停重启,要考虑权限问题和挂载的kafka/data要删除
  kafka-1:
    image: bitnami/kafka:3.5.0
    container_name: kafka-1
    #restart: always
    user: root
    ports:
      - '9092:9092'
      - '9093:9093'
    volumes:
      - /usr/local/volumes/kafka-1:/bitnami/kafka
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # 消息保留时长（毫秒），保留7天
      - KAFKA_LOG_RETENTION_MS=604800000
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    networks:
      network:
        ipv4_address: 192.168.0.28
  #### kafka ####
  kafka-2:
    image: bitnami/kafka:3.5.0
    container_name: kafka-2
    #restart: always
    user: root
    ports:
      - '9192:9092'
      - '9193:9093'
    volumes:
      - /usr/local/volumes/kafka-2:/bitnami/kafka
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # 消息保留时长（毫秒），保留7天
      - KAFKA_LOG_RETENTION_MS=604800000
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9192
    networks:
      network:
        ipv4_address: 192.168.0.29
  ###kafka-ui###
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    #restart: always
    ports:
      - '8080:8080'
    depends_on:
      - kafka-1
      - kafka-2
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_CLUSTERS_0_NAME=kafkaCluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092
    networks:
      network:
        ipv4_address: 192.168.0.30
