version: '3'
## 遇到容器不停重启，首先怀疑是挂载目录读写执行权限问题
services:
  #### mysql ####
  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/volumes/mysql:/bitnami/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=go-layout
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci

  #### redis ####
  redis:
    image: redis:7.0.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "123456"
    volumes:
      - /usr/local/volumes/redis/redis.conf:/etc/redis.conf
      - /usr/local/volumes/redis/data:/data
    environment:
      - TZ=Asia/Shanghai

  #### consul ####
  #acl配置,在/opt/bitnami/consul/conf/consul.json
  #"acl":{
  #        "enabled":true,
  #        "default_policy":"deny",
  #     "enable_token_persistence":true,
  #      "tokens": {
  #          "master": "ac9b7b85-8819-cffb-c3f6-1bbd43ca1402"
  #     }
  #  }
 ## 重置acl https://developer.hashicorp.com/consul/tutorials/security/access-control-troubleshoot#reset-the-acl-system
 # echo 13 >> bitnami/consul/acl-bootstrap-reset
 # 获取token curl -i -X PUT 'http://172.21.0.2:8500/v1/acl/bootstrap'
  consul:
    image: bitnami/consul:1.13.0
    container_name: consul
    restart: always
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - /usr/local/volumes/consul:/bitnami/consul
    environment:
      - TZ=Asia/Shanghai
      - CONSUL_AGENT_MODE=server
      - CONSUL_ENABLE_UI=true
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0

  #### jaeger ####
  jaeger:
    image: jaegertracing/all-in-one:1.37
    container_name: jaeger
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "9411:9411"
      - "16686:16686"
    environment:
      - TZ=Asia/Shanghai
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  #### prometheus ####
  ## 注意数据集data要保证其他用户可读写，直接设置777,默认存储15天,可以远程读取es持久化存储
  prometheus:
    image: bitnami/prometheus:2.37.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /usr/local/volumes/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - /usr/local/volumes/prometheus/data:/opt/bitnami/prometheus/data
    environment:
      - TZ=Asia/Shanghai

  #### grafana ####
  ##注意数据集data要保证其他用户可读写，直接设置777
  ## grafana重设密码
  ## docker exec --user 472 -it grafana /bin/bash
  ## cd /usr/share/grafana/bin
  ## ./grafana-cli admin reset-admin-password admin
  grafana:
    image: bitnami/grafana:9.2.1
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /usr/local/volumes/grafana/data:/opt/bitnami/grafana/data
      - /usr/local/volumes/grafana/grafana.ini:/opt/bitnami/grafana/conf/grafana.ini
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - prometheus

  node-exporter:
        image: bitnami/node-exporter:1.5.0
        container_name: node-exporter
        restart: always
        ports:
            - "9100:9100"