global:
  appName: go-grpc-layout
  env: dev
  version: 0.0.1
  id: 172.21.0.2
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    driver: mysql
    source: root:123456@tcp(172.21.0.2:3306)/go-layout?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    db: 0
    addr: 172.21.0.2:6379
    password: "123456"
    dialTimeout: 1s
    readTimeout: 0.4s
    writeTimeout: 0.6s
jwt:
  signingKey: some_jwt_sign_key
  expiresTime: 604800
  bufferTime: 86400
  issuer: xiaohubai@outlook.com
trace:
  endpoint: http://172.21.0.2:14268/api/traces

consul:
  host: 172.21.0.2:8500
  scheme: http
  healthCheck: false
  token: "ac9b7b85-8819-cffb-c3f6-1bbd43ca1402"
  kv:
    dictPath: dev/dict.json
  discovery:
    goGrpcLayout: "discovery://default/go-grpc-layout"

zap:
  level: "info"
  format: "json"
  filename: "./logs"
  maxSize: 1
  maxBackups: 3
  maxAge: 7
  compress: false

captcha:
  height: 80
  width: 240
  length: 6
  maxSkew: 0.7
  dotCount: 80

casbin:
  path: "./rbac_model.conf"

limiter:
  rate: 25

cors:
  mode: allow-whitelist # allow-all: 放行全部; allow-whitelist
  whitelist:
    - allowOrigin: http://www.hao123.com
      allowHeaders: Content-Type,Authorization
      allowMethods: POST, GET
      exposeHeaders: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allowCredentials: true
    - allowOrigin: chrome-extension://aejoelaoggembcahagimdiliamlcdmfm
      allowHeaders: Content-Type,Authorization
      allowMethods: POST, GET
      exposeHeaders: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allowCredentials: true

kafka:
  node:
    - topic: operationRecord
      address: [172.21.0.2:9092]

email:
  host: "smtp.qq.com"
  port: 25
  from: "1124938791@qq.com"
  isSsl: false
  secret: "bvewllmttezxjehi"
  topics:
    - name: warn
      subject: "系统告警"
      to: [xiaohubai@outlook.com]
