global:
  app_name: go-grpc-layout
  env: dev
  version: v0.0.1
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(172.12.0.2:3306)/go-layout?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    db: 0
    addr: 172.12.0.2:6379
    password: '123456'
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
auth:
  service_key: some_jwt_sign_key
  api_key: some_api_key
trace:
  endpoint: http://172.12.0.2:14268/api/traces
consul:
  address: 172.12.0.2:8500
  scheme: http
  health_check: false