global:
  appName: go-grpc-layout
  env: dev
  version: v0.0.1
  id: 172.12.0.2
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    driver: mysql
    source: root:123456@tcp(172.12.0.2:3306)/go-layout?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    db: 0
    addr: 172.12.0.2:6379
    password: '123456'
    dialTimeout: 1s
    readTimeout: 0.4s
    writeTimeout: 0.6s
jwt:
  signingKey: some_jwt_sign_key
  expiresTime: 604800
  bufferTime: 86400
  issuer: xiaohubai@outlook.com
trace:
  endpoint: http://172.12.0.2:14268/api/traces
registry:
  consul:
    host: 172.12.0.2:8500
    scheme: http
    healthCheck: false

conf:
  host: 172.12.0.2:8500
  dictPath: dev/dict.json

zap:
  level: 'info'
  format: 'json'
  filename: '../logs/log.log'
  maxSize: 1
  maxBackups: 3
  maxAge: 7
  compress: false

captcha:
  height: 80
  width: 240
  length: 6
  maxSkew: 0.7
  dotCount: 80

casbin:
  path: '../configs/rbac_model.conf'

limiter:
  rate: 2