global:
  app_name: go-grpc-layout
  env: dev
  version: v0.0.1
  id: 172.12.0.2
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
dao:
  mysql:
    driver: mysql
    source: root:123456@tcp(172.12.0.2:3306)/go-layout?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    db: 0
    addr: 172.12.0.2:6379
    password: '123456'
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
jwt:
  signing_key: some_jwt_sign_key
  expires_time: 604800
  buffer_time: 86400
  issuer: xiaohubai@outlook.com
trace:
  endpoint: http://172.12.0.2:14268/api/traces
consul:
  address: 172.12.0.2:8500
  scheme: http
  health_check: false
  configs:
    dict:
      path: /go-grpc-layout/dev/dict.yaml

zap:
  level: 'info'
  format: 'json'
  filename: '../logs/log.log'
  max_size: 1
  max_backups: 3
  max_age: 7
  compress: false

captcha:
  height: 80
  width: 240
  length: 6
  max_skew: 0.7
  dot_count: 80